# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
        exclude: newshomepages/extensions/
    -   id: end-of-file-fixer
        exclude: newshomepages/extensions/
    -   id: check-yaml
        exclude: newshomepages/extensions/
    -   id: check-added-large-files
        args: ['--maxkb=10000']
    -   id: check-byte-order-marker
        exclude: newshomepages/extensions
    -   id: check-case-conflict
        exclude: newshomepages/extensions/
    -   id: check-json
        exclude: newshomepages/extensions/
    -   id: mixed-line-ending
        exclude: newshomepages/extensions/

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        exclude: newshomepages/extensions/

-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black]
        exclude: newshomepages/extensions/

-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort

-   repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
      additional_dependencies:
        - flake8-docstrings
        - flake8-bugbear

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.931'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        exclude: newshomepages/extensions
        additional_dependencies:
          - types-requests
          - types-retry
          - types-python-slugify
          - types-pytz
          - types-PyYAML
